<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="42032" started-at="2019-02-28T10:05:52Z" finished-at="2019-02-28T10:06:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="42032" started-at="2019-02-28T10:05:52Z" finished-at="2019-02-28T10:06:34Z">
      <class name="webShop.Category">
        <test-method status="PASS" signature="setBaseURL()[pri:0, instance:webShop.Category@7113b13f]" name="setBaseURL" is-config="true" duration-ms="25899" started-at="2019-02-28T10:05:52Z" finished-at="2019-02-28T10:06:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setBaseURL -->
        <test-method status="PASS" signature="setupreport()[pri:0, instance:webShop.Category@7113b13f]" name="setupreport" is-config="true" duration-ms="1" started-at="2019-02-28T10:06:18Z" finished-at="2019-02-28T10:06:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupreport -->
        <test-method status="FAIL" signature="opewebshop()[pri:0, instance:webShop.Category@7113b13f]" name="opewebshop" duration-ms="11804" started-at="2019-02-28T10:06:18Z" finished-at="2019-02-28T10:06:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Callme - NOT FOR COMMERCIAL USE] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Callme - NOT FOR COMMERCIAL USE] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at webShop.Category.opewebshop(Category.java:98)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- opewebshop -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:webShop.Category@7113b13f]" name="getResult" is-config="true" duration-ms="2231" started-at="2019-02-28T10:06:30Z" finished-at="2019-02-28T10:06:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=opewebshop status=FAILURE method=Category.opewebshop()[pri:0, instance:webShop.Category@7113b13f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setupreport()[pri:0, instance:webShop.Category@7113b13f]" name="setupreport" is-config="true" duration-ms="0" started-at="2019-02-28T10:06:32Z" finished-at="2019-02-28T10:06:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupreport -->
        <test-method status="PASS" signature="Filteringfunction()[pri:1, instance:webShop.Category@7113b13f]" name="Filteringfunction" duration-ms="1423" started-at="2019-02-28T10:06:32Z" finished-at="2019-02-28T10:06:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Filteringfunction -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:webShop.Category@7113b13f]" name="getResult" is-config="true" duration-ms="277" started-at="2019-02-28T10:06:33Z" finished-at="2019-02-28T10:06:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Filteringfunction status=SUCCESS method=Category.Filteringfunction()[pri:1, instance:webShop.Category@7113b13f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:webShop.Category@7113b13f]" name="tearDown" is-config="true" duration-ms="1" started-at="2019-02-28T10:06:34Z" finished-at="2019-02-28T10:06:34Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.aventstack.extentreports.ExtentReports.removeTest(ExtentReports.java:258)
at webShop.Category.tearDown(Category.java:188)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- webShop.Category -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
